CREATE TABLE COMMENTER (
    EMAIL NVCHAR(256) NOT NULL UNIQUE,
    USERNAME NVCHAR(256) NOT NULL UNIQUE
);
CREATE TABLE COMMENT (
    CREATED_TIME INT NOT NULL,
    CONTENT NVCHAR(512) NOT NULL,
    COMMENTER INT NOT NULL,
    POST INT NOT NULL,
    FOREIGN KEY(COMMENTER) REFERENCES COMMENTER(ROWID),
    FOREIGN KEY(POST) REFERENCES POST(ROWID)
);
CREATE TABLE POST (
    CREATED_TIME INT NOT NULL,
    MODIFIED_TIME INT NOT NULL,
    CONTENT TEXT NOT NULL,
    TITLE NVCHAR(255) NOT NULL,
    VIEWS INT NOT NULL,
    AUTHOR NVCHAR(127) NOT NULL, PUBLISHED INT NOT NULL, COVER_URL NVCHAR(255) NOT NULL
);
CREATE TABLE IPMAP (
    IPID INT NOT NULL,
    POSTID INT NOT NULL, TIME INT NOT NULL default 0,
    FOREIGN KEY(POSTID) references POST(ROWID),
    FOREIGN KEY(IPID) references IPADDR(ROWID),
    UNIQUE(IPID, POSTID)
);
CREATE TABLE IPADDR (
    IP INT PRIMARY KEY NOT NULL,
    UNIQUE(IP)
);
